### ISSUE TITLE
LibNPKI.dll 

### ISSUE THREAD

**Issue by Moonachi** [LiteHell/CoalaMC_Shrine#1]
해당 dll 파일은 직접 만드신 건가요?
어디서 받을 수 있는지 궁금합니다.

**Comment by LiteHell** [comment]
이 래포에 그 파일이 있나요?

**Comment by Moonachi** [comment]
> 이 래포에 그 파일이 있나요?

뭐지... 분명 해당 에러가 표시되었는데 다시 실행보니 잘 됩니다. 감사합니다.

그런데 혹시 '개인키 내보내기'에서 'PKCS#1 RSA Private Key + DER' 해당 문장이
개인키를 der로 내보낸다는 말인가요?

**Comment by Moonachi** [comment]
> 이 래포에 그 파일이 있나요?

아 뭔가 이상하다고 했는데 레포를 잘못 지정했네요 ...
https://github.com/LiteHell/NPKI_example 해당 레포입니다.

**Comment by LiteHell** [comment]
> > 이 래포에 그 파일이 있나요?
> 
> 뭐지... 분명 해당 에러가 표시되었는데 다시 실행보니 잘 됩니다. 감사합니다.
> 
> 그런데 혹시 '개인키 내보내기'에서 'PKCS#1 RSA Private Key + DER' 해당 문장이
> 개인키를 der로 내보낸다는 말인가요?

네 맞습니다

**Comment by Moonachi** [comment]
> > > 이 래포에 그 파일이 있나요?
> > 
> > 
> > 뭐지... 분명 해당 에러가 표시되었는데 다시 실행보니 잘 됩니다. 감사합니다.
> > 그런데 혹시 '개인키 내보내기'에서 'PKCS#1 RSA Private Key + DER' 해당 문장이
> > 개인키를 der로 내보낸다는 말인가요?
> 
> 네 맞습니다

우선 저도 개인키 공개키 보고 있었는데 해당 코드 보면서 참고해보겠습니다.
좋은 예제 감사합니다 ^^.

**Comment by Moonachi** [comment]
저 하나만 더 여쭤보겠습니다. 
(인증서 선택 -> 비밀번호 확인 후 실행되는 코드) 아래 코드 부분에서 확인에 실패했다고 표시가 되는데 비밀번호가 일치해서 다음 코드가 실행되는데 False가 나오는 이유(경우)를 알 수 있을까요?
return 값이 False여서 "확인에 실패했습니다." 라고 표시가 되어 문의 드립니다.

아니면 비밀번호만 통과되면 상관없나요?
 
![image](https://user-images.githubusercontent.com/46507959/85282054-0514e080-b4c6-11ea-9f95-982d03cc0db3.png)

**Comment by LiteHell** [comment]
주민등록번호 잘못 쳤을때 뜹니다. 그리고 여기말고 NPKI_example 레포에서 대화해주시면 감사하겠습니다.

**Comment by Moonachi** [comment]
네 추가 궁금사항 해당 레포에서 문의 드리겠습니다.
